spring.application.name=PanelaMagica

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/panela-magica/v3/api-docs

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/panela-magica/swagger-ui.html


spring.datasource.url=jdbc:postgresql://localhost:5433/panela_magica
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.jpa.hibernate.ddl-auto=update

# JWT (em produção defina a variável de ambiente JWT_SECRET com 32+ caracteres)
jwt.secret=A6E0mw7buGIDozs8X+yM64Oqq11Q9AluAkwX8xKipDY=
jwt.expiration-minutes=60
cors.allowed-origins=http://localhost:3000,http://localhost:5173,http://localhost:4200

# application.properties
logging.level.root=INFO
logging.level.com.todolist=DEBUG
logging.level.org.springdoc=WARN
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web.servlet.mvc.method.annotation=ERROR
